"""
Crawl Analytics Script
Analyzes site data from a JSONL file and word frequencies from a DBM file.

Usage: python3 analyze_crawl.py <site_data.jsonl> <word_frequencies.dbm>

Generated by Claude Sonnet 4.6
"""

import dbm
import json
import sys
from collections import defaultdict
from urllib.parse import urlparse, urldefrag


# ---------------------------------------------------------------------------
# Stop words
# ---------------------------------------------------------------------------

def get_stop_words() -> set[str]:
    """Return a set of English stop words from the 'stop-words' package,
    falling back to a compact built-in list if the package is unavailable."""
    try:
        from stop_words import get_stop_words as _get
        return set(_get("english"))
    except ImportError:
        # Minimal NLTK-style fallback so the script still runs without the lib
        fallback = {
            "a", "about", "above", "after", "again", "against", "all", "am",
            "an", "and", "any", "are", "aren't", "as", "at", "be", "because",
            "been", "before", "being", "below", "between", "both", "but", "by",
            "can't", "cannot", "could", "couldn't", "did", "didn't", "do",
            "does", "doesn't", "doing", "don't", "down", "during", "each",
            "few", "for", "from", "further", "get", "got", "had", "hadn't",
            "has", "hasn't", "have", "haven't", "having", "he", "he'd", "he'll",
            "he's", "her", "here", "here's", "hers", "herself", "him",
            "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm",
            "i've", "if", "in", "into", "is", "isn't", "it", "it's", "its",
            "itself", "let's", "me", "more", "most", "mustn't", "my",
            "myself", "no", "nor", "not", "of", "off", "on", "once", "only",
            "or", "other", "ought", "our", "ours", "ourselves", "out", "over",
            "own", "same", "shan't", "she", "she'd", "she'll", "she's",
            "should", "shouldn't", "so", "some", "such", "than", "that",
            "that's", "the", "their", "theirs", "them", "themselves", "then",
            "there", "there's", "these", "they", "they'd", "they'll",
            "they're", "they've", "this", "those", "through", "to", "too",
            "under", "until", "up", "very", "was", "wasn't", "we", "we'd",
            "we'll", "we're", "we've", "were", "weren't", "what", "what's",
            "when", "when's", "where", "where's", "which", "while", "who",
            "who's", "whom", "why", "why's", "will", "with", "won't",
            "would", "wouldn't", "you", "you'd", "you'll", "you're", "you've",
            "your", "yours", "yourself", "yourselves",
        }
        print(
            "[warning] 'stop-words' package not found; using built-in fallback list.\n"
            "          Install it with:  pip install stop-words\n",
            file=sys.stderr,
        )
        return fallback


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def normalize_url(raw_url: str) -> str:
    """Strip the fragment from a URL so #anchors don't create duplicate pages."""
    defragged, _ = urldefrag(raw_url)
    return defragged.rstrip("/")   # also strip trailing slash for consistency


def is_uci_subdomain(hostname: str) -> bool:
    """Return True if hostname is *.uci.edu (including uci.edu itself)."""
    return hostname == "uci.edu" or hostname.endswith(".uci.edu")


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def load_site_data(jsonl_path: str) -> list[dict]:
    """Parse every line of the JSONL file into a list of dicts."""
    records = []
    with open(jsonl_path, "r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                print(f"[warning] Skipping malformed JSON on line {lineno}: {exc}", file=sys.stderr)
    return records


def load_word_frequencies(dbm_path: str) -> dict[str, int]:
    """Read all key/value pairs from the DBM file."""
    with dbm.open(dbm_path, "r") as db:
        return {key.decode(): int(db[key].decode()) for key in db.keys()}


# ---------------------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------------------

def q1_unique_pages(records: list[dict]) -> tuple[int, set[str]]:
    """
    Q1 – How many unique pages?
    Uniqueness is defined by the URL *after* stripping the fragment.
    Returns (count, set_of_unique_normalized_urls).
    """
    seen: set[str] = set()
    for rec in records:
        seen.add(normalize_url(rec["url"]))
    return len(seen), seen


def q2_longest_page(records: list[dict]) -> tuple[str, int]:
    """
    Q2 – Which page has the most words?
    When the same normalized URL appears multiple times, use the max word count
    (e.g. a re-crawl that captured more content).
    Returns (url, word_count).
    """
    best_url = ""
    best_count = -1
    seen: dict[str, int] = {}
    for rec in records:
        url = normalize_url(rec["url"])
        count = int(rec.get("word_count", 0))
        if seen.get(url, -1) < count:
            seen[url] = count
            if count > best_count:
                best_count = count
                best_url = url
    return best_url, best_count


def q3_top50_words(
    word_freq: dict[str, int],
    stop_words: set[str],
    n: int = 50,
) -> list[tuple[str, int]]:
    """
    Q3 – Top-50 most common words across all crawled pages, ignoring stop words.
    Returns a list of (word, frequency) sorted descending by frequency.
    """
    filtered = {
        word: freq
        for word, freq in word_freq.items()
        if word.lower() not in stop_words and word.isalpha()
    }
    return sorted(filtered.items(), key=lambda x: x[1], reverse=True)[:n]


def q4_uci_subdomains(unique_urls: set[str]) -> list[tuple[str, int]]:
    """
    Q4 – Subdomains under uci.edu with their unique-page counts.
    Returns a list of (subdomain, count) sorted alphabetically by subdomain.
    """
    subdomain_pages: dict[str, set[str]] = defaultdict(set)
    for url in unique_urls:
        parsed = urlparse(url)
        host = parsed.hostname or ""
        if is_uci_subdomain(host):
            subdomain_pages[host].add(url)
    return sorted(
        ((sub, len(pages)) for sub, pages in subdomain_pages.items()),
        key=lambda x: x[0],
    )


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def section(title: str) -> None:
    width = 70
    print()
    print("=" * width)
    print(f"  {title}")
    print("=" * width)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: python3 analyze_crawl.py <site_data.jsonl> <word_frequencies.dbm>")
        sys.exit(1)

    jsonl_path, dbm_path = sys.argv[1], sys.argv[2]

    # ---- Load data --------------------------------------------------------
    print(f"Loading site data from:       {jsonl_path}")
    records = load_site_data(jsonl_path)
    print(f"  → {len(records):,} raw records loaded")

    print(f"Loading word frequencies from: {dbm_path}")
    word_freq = load_word_frequencies(dbm_path)
    print(f"  → {len(word_freq):,} unique words loaded")

    stop_words = get_stop_words()

    # ---- Q1 ---------------------------------------------------------------
    section("Q1 — Unique Pages")
    unique_count, unique_urls = q1_unique_pages(records)
    print(f"  Total unique pages (by URL, fragment ignored): {unique_count:,}")

    # ---- Q2 ---------------------------------------------------------------
    section("Q2 — Longest Page (by Word Count)")
    longest_url, longest_count = q2_longest_page(records)
    print(f"  URL:        {longest_url}")
    print(f"  Word count: {longest_count:,}")

    # ---- Q3 ---------------------------------------------------------------
    section("Q3 — Top 50 Words (stop words excluded)")
    top50 = q3_top50_words(word_freq, stop_words)
    col_w = max((len(w) for w, _ in top50), default=10) + 2
    print(f"  {'Rank':<6} {'Word':<{col_w}} {'Frequency':>12}")
    print(f"  {'-'*6} {'-'*col_w} {'-'*12}")
    for rank, (word, freq) in enumerate(top50, 1):
        print(f"  {rank:<6} {word:<{col_w}} {freq:>12,}")

    # ---- Q4 ---------------------------------------------------------------
    section("Q4 — UCI.edu Subdomains (alphabetical)")
    subdomains = q4_uci_subdomains(unique_urls)
    print(f"  Total subdomains found: {len(subdomains):,}\n")
    for sub, count in subdomains:
        print(f"  {sub}, {count}")

    print()


if __name__ == "__main__":
    main()