"""
File made for debugging purposes to display dbm word frequencies to the shell.

Generated by Claude Sonnet 4.6
"""

import dbm
import sys

def display_dbm(filename: str) -> None:
    with dbm.open(filename, 'r') as db:
        for key in db.keys():
            print(f"{key.decode()}: {db[key].decode()}")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python3 display_dbm.py <filename>")
        sys.exit(1)
    display_dbm(sys.argv[1])