"""
File made for debugging purposes to display dbm word frequencies to the shell.

Generated by Claude Sonnet 4.6
"""

import dbm
import sys

def display_dbm(filename: str) -> None:
    with dbm.open(filename, 'r') as db:
        entries = {key.decode(): int(db[key].decode()) for key in db.keys()}
    
    for word, count in sorted(entries.items(), key=lambda x: x[1]):
        print(f"{word}: {count}")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python3 display_dbm.py <filename>")
        sys.exit(1)
    display_dbm(filename=sys.argv[1])